apiVersion: v1
kind: ConfigMap
metadata:
  name: goapp-map
data:
  RUN_MODE: "k8s-staging"
---
# RPOD 共用
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: virtualservice
#   labels:
#     k8s-app: goappk8s
# spec:
#   hosts: 
#     - "zeki.jvid.com"
#   http:
#     - route:
#         - destination:
#             host: staging-goapp-svc
#             port:
#               number: 8080
