name: Go
on:
  push:
    branches: [ main,master ]
jobs:
  build:
    name: Build & Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  docker:
    needs: build
    name: Build & Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
  release:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15