name: Go
on:
  push:
    branches: [ main,master ]
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
  docker-build:
    needs: unit-test
    name: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
  docker-test:
    needs: unit-test
    name: docker-test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
  upload-image:
    needs: [docker-build,docker-test]
    name: upload-image
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
  release:
    needs: docker-build
    name: Release to GCP
    runs-on: ubuntu-latest
    steps:
    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: project_id
        export_default_credentials: true
    - name: gcloud-auth
      run: |-
          ehco "do"
#         gcloud --quiet auth configure-docker
    - name: gcloud-set
      run: |-
          ehco "do"
#         gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Build Publish
      run: |-
          ehco "do"
#         VERSION="g."$GITHUB_RUN_ID
#         echo "$VERSION"
#         IMAGE_REPO="asia.gcr.io/cheep2workshop"
#         docker build -t ${IMAGE_REPO}/nd-director:${VERSION} ./nd-director
#         docker build -t ${IMAGE_REPO}/nd-frontend:${VERSION} ./nd-frontend
#         docker build -t ${IMAGE_REPO}/nd-matchfunction:${VERSION} ./nd-matchfunction
#         docker push ${IMAGE_REPO}/nd-director:${VERSION}
#         docker push ${IMAGE_REPO}/nd-frontend:${VERSION} 
#         docker push ${IMAGE_REPO}/nd-matchfunction:${VERSION} 
        # MAC sed -i '' "s/_VERSION/$VERSION/" ./nd-om.yaml
#         sed -i "s/_VERSION/$VERSION/" ./nd-om.yaml
    - name: GKE-deploy
      run: |-
          ehco "do"
#         kubectl apply -f ./nd-om.yaml
  intergration-tests:
    needs: release
    name: Intergration Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
